version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
    # Security updates only
    open-pull-requests-limit: 0
    ignore:
    - dependency-name: '*'
