version: '3.8'

services:
  disclosures:
    container_name: disclosures
    build:
      dockerfile: docker/Dockerfile
      context: .
    image: freelawproject/disclosures
    networks:
      - cl_net_overlay

  mock_courtlistener_disclosures:
    container_name: mock_courtlistener_disclosures
    image: freelawproject/disclosures
    networks:
      - cl_net_overlay
    depends_on:
      - disclosures

networks:
  cl_net_overlay:
    driver: bridge
    external: true


