version: '3.8'

services:
  disclosures:
    container_name: disclosures
    build:
      dockerfile: docker/Dockerfile
      context: .
    image: freelawproject/disclosures
    ports:
      - "5050:5050"
