version: '3.8'

services:
  cl-disclosures:
    container_name: cl-disclosures
    build:
      dockerfile: docker/Dockerfile
      context: .
    image: freelawproject/disclosure-extractor:latest
    networks:
      - cl_net_overlay

  mock_cl_disclosures:
    container_name: mock_cl_disclosures
    image: freelawproject/disclosure-extractor:latest
    networks:
      - cl_net_overlay
    depends_on:
      - cl-disclosures

networks:
  cl_net_overlay:
    driver: bridge
    external: true


